"""delete crag

Revision ID: 560fe18fabf4
Revises: a10922ccc018
Create Date: 2023-03-29 09:44:25.968530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '560fe18fabf4'
down_revision = 'a10922ccc018'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_column('crag_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('crag_name', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
