"""create tables

Revision ID: 85377d7ae1bc
Revises: 5597ce329fe2
Create Date: 2023-05-03 18:28:26.511841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85377d7ae1bc'
down_revision = '5597ce329fe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    # ### end Alembic commands ###
