"""create tables

Revision ID: 96e4816cc50b
Revises: 
Create Date: 2023-03-27 18:25:19.574888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96e4816cc50b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_routes_review_id_reviews', type_='foreignkey')
        batch_op.drop_column('review_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_routes_review_id_reviews', 'reviews', ['review_id'], ['id'])

    # ### end Alembic commands ###
